---
title: 'Identification methods on industrial agglomerations: a survey'
author: "Jaime A. Prudencio Vázquez"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float: true
    highlight: pygments
bibliography: referencias.bib
csl: regional-science-and-urban-economics.csl
---

## Abstract

Among academic work, it seems there is no doubt about the possibility of spatially concentrated patterns of economic activity to generate some gains in the firms performs involved. These activity agglomerations have been called in a variety of different ways, depending on complexity of the analyzed phenomena: industrial districts, industrial complex, regional productive systems, regional innovation systems or clusters, among others. It is common that policy makers opt to take some policy based on the notion of agglomeration advantages to promote regional growth and development. Nevertheless, a not clear distinction of the meaning of these terms and some times their interchangeability usage cause ambiguity, and then obstacles for their empirical identification. Besides, certainly linked to the previous reason, there are not a clear consensus on methodologies to identify such a spatially concentrated patterns of economic activity. The objective of this paper is twofold. First, it seeks to contribute to clarify the meaning of the different concepts used to describe spatially concentrated patterns of economic activity through a critical compare. Second, based on the previous distinction, it makes a survey on the existing methods for identification  in international literature and specifically in Mexico in the last ten years.


## Introduction

Economic activity is not homogeneously distributed on the space, it is concentrated at some places rather [@WorldBank2009]. Names received for those **economic activity concentration patterns** (EACP) in specialized literature are varied: industrial complexes, industrial clusters, regional productive agglomerations, regional innovative systems, milleaux innovative, and others. The reasons for this diversity are associated to the complexity and linkages with other social phenomenons. Even so within the same concept are various interpretations, and this may cause some confusion.

Gordon and MacCann [-@GordonAndMacCann2000] remark the ambiguity on the cluster term and point out the emerging obstacles to their empirical testing. This concept had received sever criticism from Martin and Sunley [-@MartinSunley2003] in a theoretical and empirical way. The term "localized industries" (coined by Marshall to describe economic related activities concentrated in specific places) is used sometimes without consider the historical context in which it emerged: it was devised to describe the spatial concentration of small and medium firms (SMEs) to describe the beheivoir of workers and suppliers in the nineteenth century [@TripplBergman2014: 450]. Some terms, like neo-marshallian industrial district, include sometimes vague ideas ("entrepreneur or industrial atmosphere") in an attempt to include non economic factors, like culture and institutions  and the milleaux innovative concept often is not enough clear to distinguish it to the network concept. All of this causes difficult to understand and measure the EACP.  

There have been attempts to make the concepts related to EACP more clear. Trippl and Bergman [-@TripplBergman2014] distinguish among industrial districts, innovative milieus, and industrial clusters. They point out similarities and differences based on spatial dimension, main participants and their motivations and interactions. Gordon and MacCann [-@GordonAndMacCann2000] describe the differences in three clear theories to EACP: the model of pure agglomeration in the Marshall point of view, the industrial-complex model and the social-network model. They remake their differences according to the existent evidence that soport the theorical models and their policy implications. These conceptual diversity is associated to even more vast quantity of methodological approaches to identify EACP. That is, there is no a unique term or concept to describe the EACP, but even within the same term, the methodological diversity is present [@Komorowski2020]. Cruz and Teixeira [-@CruzTeixeira2010] survey the evolution of the cluster literature thought bibliometric techniques in the 1962-2008 period. They identify and group  those studies concerning to methods and measures and they show these kind of studies were fecund in seventies, especially those that concern on conceptualization of analytical methods.  

Because the main problem with EACP from a technical point of view is the _pattern identifications_, studding the methods to identify clusters is very close to computational techniques such as clustering and groping methods [@Adolfsson-etal2018]. Multiples studies in regional economics use methods based on the identification of input-output linkages on a national economy [@FeserBergman2000; @Feser-etal2005; @Sonis2008; @Delgado-etal2016; @GonzalezVillareal2017; @LagunaReyes2010; @TrejoNegrete2018]. Others perform their analysis using measures of agglomeration or specialization [@Kopczewska-etal2017; @Komorowski2020; @Gleave-etal2004; @GarciaCastro2008], or case study on management persective [@Piccinetti2015]. The most recent methodological approaches try to fix some weakness of the classical methods using better algorithms [@AlmasriAndShukur2008], introducing techniques to deal with microlevel data [@BonneuThomas2015] or introducing network analysis [@Sheresheva-etal2022]. Nevertheless, despite the topic of methods of identification of EACP is a prolific field in the regional science,  just a few critically evaluate the used concept [@GonzalezVillareal2017].

The policy purposes of the studies on concentration economic activity identification are also relevant. The academic consensus related to the agglomeration economies on the potential benefits of the agglomerated activities over firms, region and whole economy, makes identification of such agglomerations the first step to reinforce them [@Komorowski2020]. So that, it is possible to identify a necessity to discus the strength and weakness of the available identification methods not only for academic and scientific purposes, but because their potential use to policy makers. 

*The objective of this paper is twofold. First, it seeks to contribute to clarify the meaning of the different concepts used to describe EACP through a critical compare. Second, based on the previous distinction, it makes a survey on the existing methods for identification  in international literature and specifically in Mexico in the last ten years. The remaining of this document has the following structure. In the next section, a critical distinction on different concepts on EACP is given. Then, the different concepts are related to specific methods used to the identification of those specific conception of EACP in the empirical literature, where the strengths and weaknesses are pointed out. Finally, a short reflection on the found methods and their policy implications for Mexican regional industrial policy is presented.*


## Three ideas for EACP concepts analysis

*In this section three ideas are discussed. First, the causes of the EACP, the economic agglomeration forces, are explained in a glance. Second, a short exposition of those concepts is given, and finally, three key criteria are pointed in order to figure out critically the concepts used in specialized literature to name the EACP*

A central research topic in Regional Science has been the forces shaping economic space [@Fischer2014]. That driving forces, called agglomeration economies, are linked to the advantages that economic units receive of such a spatial pattern [@GordonAndMacCann2000: 516]. Those advantages emerge from the social and cooperative character of the labor production process [@Marx2011] and the social labor division [@Scott2006] and influence firms performance which benefit with cost reductions from different sources (Cohen and Morrison, 2009). Usually, agglomeration economies are divided in two types: i) agglomeration economies of specialization or Marshall-Arrow-Romer (MAR) and they refer agglomeration of firms of the same industry (**Glaeser, 1992; Sjöholm, 1999: 560; @TripplBergman2014**), and ii) urbanization economies or Jacobs economies where is not the specialization, but the diversity and variety of geographical economic concentrated activities that could promote innovation and growth [@Duranton2014; @VanOortAndLambooy2014]. 

Those forces, agglomeration economies, configurate a certain spatial patter of the firms:  economic activity concentration patterns. Those EACP have been called in different ways: industrial districts, industrial complex, industrial poles, regional productive systems, regional innovation systems or clusters. This variety of concepts may cause confusion because sometimes they are used interchangeably and it is not usual a critical reflection on their scope, neither theoretical nor empirical. Here it is proposed three criteria to understand and distinguish among the multiple existent concepts related to EACP: i) phase of capitalist development in which it was coined, ii) the extension of the social reality captured by the concept and iii) the type of firms linked in the agglomeration.

The first criteria is a historical one: the capitalist development period in which terms were coined. EACP concepts were created with a range of almost one hundred years of difference. Changes in organization of the manufacture processes due the technological development on transports, use of new energy sources and managerial principles affect all of them forces that cause de EACP and their specific form. More over, the self structure of the capitalism have change on those period: from a phase of competitive behaviour centered in local markets, to a oligopolic structure of multinational enterprises (MNE) that supply national markets, and then to a network of global intermediate suppliers governed for the MNE in a global value chains.

This differences on capitalism phases have to take into count to avoid apply a term coined one hundred of years ago in the same sense in which it was created. For example, industrial district term was proposed by Marshall in the begging of the Twenty Century to reflect a kind of society that was in extinction: little  manufacturers focused to serve local markets [@TripplBergman2014: 450]. On the other hand, the neo-marshalian term it is about semi or even not capitalist production were the craftsman authority and the place tradition is relevant. The attention to the social, institutional and cultural variables given by the Neo-Marshallians and their emphasis on the small and medium enterprises (SME) resembles, in some way, to the competitive phase of capitalism.

The second criteria is a delimitative one: the scope of the social reality captured by the concept. Some of the EACP are narrower than others. This is because they center their attention only on the economic phenomenons (input-output linkages, cost reduction, enhancing productivity) like industrial complex or some times industrial district. Some others are more comprehensive capturing not only the economic aspects but sociological, cultural and institutional factors like innovative milleaux or regional innovation systems. 

Finally, the third is a structural one: the type of firms involved in the agglomeration. The used EACP concept have to take in count the kind of firms participating on the agglomeration, that is, whether is structured by SME or MNE: is the firm family owned? Is the little firm leaded by the first or second capitalist generation? Or it is a corporative firm structure? For example, the Porter´s cluster concept are more close to the MNE analysis than the local productive system that usually describe SME. This is particularly relevant when innovation and knowledge dissemination processes are discussed because the abailable resources to investigation and develop ment are very different between SME and MNE.  Besides, this distinction take relevance for the development processes too, because the interests of the owners on the region development where the firm is located may vary deeply if the firms is owned by national or multinational capital.

In the next lines, concepts related to the EACP are disscused at the light of the previous ideas. Particulary, the treated concepts are: industrial district (marshallian and neo-Marshallian), innovative milieus and regional innovation system, growth pole, industrial cluster,industrial complex, regional productive system and local productive agglomerations.

## Some common EACP concepts

As is well known, Marshall (**1920**) describes the causes and consequences of activity agglomerations in what he called industrial districts. He linked spatial agglomeration to three forces: i) knowledge spillovers, ii) rise of supplier industries and iii) labor market effects. They are describing a reminiscence of the competitive phase of capitalism where the agglomerated small and medium (SMEs) enterprises take advantages from the rise of agglomeration economies and they are able to compete with large dominant firms. Nevertheless, "the Marshallian district was essentially limited by distances that could be economically traversed daily by workers and suppliers in the late nineteenth century, the densities of which were sufficiently high and distances sufficiently short that districts could often be referred to as 'neighborhoods'" [@TripplBergman2014: 449-450]. The marshallian industrial district concept was predominantly refered to: a competitive phase of capitalism, it emphasizes on economic phenomena and center the attention on SME.

During the capitalism golden age, there was various attempts to theorize about the regional development process on the lagged economies in a regional context. Among them, Perroux's contribution, the well known growth poles theory, was "characterized by the use of huge financial and fiscal incentives to external large firms and the idea of imitation and reproduction of the development conditions and organizations already experienced in developed region" [@Garofoli2020encyclopedia: 199]. The Perroux´s concept on EACP was coinden on the oligopolic phase of the capitalism, where the big MNE provide national markets and was lightly linkedwith national and smaller firms. The growth pole theory  paid close attention to the economic factors and less to institutional, social and cultural.

In the 70s, in the meddle of a generalized global crisis that mark the transition to the domain of the GVC as form of dominant production, some SME in Italy find the way to survive taking advantages not only from physical proximity, but many social and cultural situations. The studies by Becattini (1979) and their contributors on causes of success of the Third Italy bring the concept of Neo-Marshallian Industrial Districts where the economic variables were important but far from beeing the only determinant of development success. Becattini describe the Neo-Marshallian Industrial Discrict as "complex socioeconomic settings and highlighted the relation between efficiency and competitiveness of production and the sociocultural conditions prevailing at the regional level" [@TripplBergman2014: 444].

At the same time, in France in the late 1970s, another concept arose and it was used to describe a capable regions to generate and promote growth based on innovations: Milieux Innovateurs, a concept particularly extended on French researches, and sometimes used interchangeably by **network** concept [@Gallaud2013encyclopedia]. Trippl and Bergman (2021: 444) define a milieu "as a set of region-specific rules, practices,and institutions that enhances the capacity of regional actors to innovate and to coordinate with other innovative actors". Once again,  the concepts goes beyond the pure economic aspects of the agglomerated activities and remark the role of innovation. An attempt to extend the concerned phenomenon on the innovation process from a territorial point of view, some are proposed the concept of _territorial production system_ (Crevoisier and Maillat, 1991; cited by @TripplBergman2014: 446), which is less clear in their scope.

All of them, Neo-Marshallian Industrial Discrict, Milieux Innovateurs and territorial production system emerge in a transition phase from the oligopolic to the open market global production organizated process. Besides, the concepts give more attention to the social, institutional and cultural factors that may enhance or condition the economic success of SME.

A very close term used in the economic urban literature is _industrial complex_, they are "characterised  by  sets  of identifiable and stable relations among firms which are in part manifested in their spatial behaviour. The relations are conceived primarily in terms of trading links, and it is these patterns of sales and purchases which are seen as principally governing their locational behaviour" [@GordonAndMacCann2000: 518]. This concept emerge approximately in the same transition phase but center its attention the more in economic factors than the social or institutional ones. Besides, it seems to refer to MNE than SME.

Maybe the most popular concept related to EACP is the cluster term. The popularity and international dissemination of the cluster concept is due to the Porter´s work on _corporate strategies_, and refers usually those kind of firms. Weighing more the competitive rather the cooperative aspects of a cluster, Porter defines them as  "geographic concentrations of interconnected _companies_, specialized suppliers, service providers, firms in related industries, and associated institutions in particular fields that compete but also cooperate” [Porter 1998, p. 197, cited by @TripplBergman2014: 447]. Nevertheless, the concepts has received many criticism because its ambiguity [@MartinSunley2003; @Pacheco2007], the lack of precision on geographical and sectorial limits, and the little attention paid the social factors linked to clusters.


## Measuring EACP: methodological approaches

Some introductions words

@Komorowski2020 describe and compare three different traditional methods to identify industrial clusters: relative indexes on employment, normalized and transformed location quotients on employment and dot maps to see visual patterns. He illustrate this method using data from media industry from Brussels and find that all of them show limitations in: identifying the extent and location of the studied cluster, availability of the data used and some distortions due to the presence of large enterprises and the scale of the spatial unit and  (p. 98).


Top-down

In words of @LagunaReyes2010, this approach "allows the identification of production chains at the regional level, based on national grouping patterns. This makes it possible to identify the gaps between local supply chains compared to national ones, which makes it possible to determine areas of specialization, regional competitive advantages and regional development opportunities" (p. 127).

@TrejoNegrete2018 say that the Feser and Bergman Method "meets five criteria that make it a useful tool to identify groupings, when input-output information is available, which are: a) reliability; b) ability to generate results in the short term; c) low instrumentation cost; d) possibility of sectorial disaggregation of the information and e) flexibility to visualize the presence of clusters in different geographical areas.


On the other hand, this approach has some weakness "since by using the national economy as a reference, it implicitly assumes that the differences in technology, labor productivity and consumption patterns between the national economy and local economies are null, which can be misleading, especially in cases in which the region truly specializes in a particular production chain" (p. 127). 

### Top down aproache

#### Studies to Mexico

@MendozaVelazquez2017 appeals to the Porter's approach based on US Clusters Mapping by Institute for Strategy
and Competitiveness from Harvard Business School. Mendoza Velasquez identify 41 clusters of traded industries, it is, activities whose localization rarely depend on geographical conditions and natural endowments. From these, "eight out of which are classified as high-technology clusters, 10 as service clusters and 23 as other manufacturing industries clusters. Each cluster contains on average 28 industries" [@MendozaVelazquez2017: 415]

@GonzalezVillareal2017 seek to identify for Mexico what they call industrial complexes with the objective to propose some economic policy ideas in the frame of smart specialization and related variety. The used method is divided in two stages: first, the identify the relevant industrial productive chains through the Feser and Bergman [-@FeserBergman2000] method; secondly, the identified relevant productive chains are then spatialized by means of location quotients from employment for local economies. The authors find out five value chains concentrated in several regional complexes: electronics component  manufacturing (12 complexes),  automobiles (18 complexes),  chemicals (39 complexes), textiles and apparel (38 complexes), and agricultural and processed food (43 complexes).

In the same fashion, the work of @LagunaReyes2010 tries to find industrial clusters in the Mexican regions thought the Feser and Bergman (2000) technique and an extension  based on Rey and Mattheis (2000). He uses a Input-Ouput Matrix for Mexican economy to 76 activities in 1996. He idenfied 12 productive chains: Metalworking and automotive, Non-metallic minerals and other metallic products, Chemicals, Food products, Energy and derivatives, Textiles, Electronics and its parts, Paper and cardboard products, Inputs for the production of auto parts, Non-ferrous metals and their products, Leather products and Animal food. Nevertheless, he doesn't address the regions where the clusters are.

Using the FBA, @NietoNegrete2018 identify six clusters in the central region of Mexico (Mexico City, Mexico State, Hidalgo, Querétaro, Puebla, Tlaxcala, Morelos) grouping 21 of the 28 sectors of the regional IOM they used in their study: Consumer services, Superior services, Construction and housing, Agribusiness, Chemicals and Miscellaneous manufacturing.







## Referencias faltantes

GLAESER, E. L., Kallal, H. D., Scheinkman, J. A. y Shleifer A. (1992). “Growth in Cities”. Journal
of Political Economy, Vol. 100, No. 6, Centennial Issue (Dec., 1992), pp. 1126-1152. The
University of Chicago Press.


SJÖHOLM, F. (1999). “Productivity growth in Indonesia: the role of regional characteristics and
direct foreign investment”. Economic Development and Cultural Change, 47(3), 559-584.


COHEN, J. P., & Paul, C. J. M. (2009). Agglomeration, productivity and regional growth:
production theory approaches. Handbook of regional growth and development theories, 101-117.


Marshall, Alfred 1842-1924    Principles of economics :   an introductory volume /    Philadelphia   Porcupine Press   1982





