---
title: "Complejos industriales regionales en Mexico"
author: "Jaime A. Prudencio-Vázquez"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: yes
  pdf_document:
    toc: yes
    latex_engine: xelatex
  html_document:
    theme: cerulean
    toc: yes
    toc_float: yes
    highlight: pygments
bibliography: aglomeraciones.bib
csl: "regional-science-and-urban-economics.csl"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE,message = FALSE)
```

# Abstract (ckeck)

Among academic work, it seems there is no doubt about the possibility of spatially concentrated patterns of economic activity to generate some gains in the firms performs involved. These activity agglomerations have been called in a variety of different ways, depending on complexity of the analyzed phenomena: industrial districts, industrial complex, regional productive systems, regional innovation systems or clusters, among others. It is common that policy makers opt to take some policy based on the notion of agglomeration advantages to promote regional growth and development. Nevertheless, a not clear distinction of the meaning of these terms and some times their interchangeability usage cause ambiguity, and then obstacles for their empirical identification. Besides, certainly linked to the previous reason, there are not a clear consensus on methodologies to identify such a spatially concentrated patterns of economic activity. The objective of this paper is twofold. First, it seeks to contribute to clarify the meaning of the different concepts used to describe spatially concentrated patterns of economic activity through a critical compare. Second, based on the previous distinction, it makes a survey on the existing methods for identification  in international literature and specifically in Mexico in the last ten years.


# Introduction

Industry, particularly manufacturing, has played a central role in the process of long-term growth and development in national economies. This is explained by the increase in labor productivity and the advantages derived from the spillover effects of productive linkages, which are more intense in industry than in services or agriculture [@Szirmai2012].

During the period of import substitution in Mexico, the industrial policy based on the premise of the industrialization and development binomial was driven through active measures of intervention and financing to the industrial sector [@Cordera1981]. However, with the rise of neoliberalism, the dominant economic thinking turned economic policy indifferent to the activity sector, considering that the promotion of finance, services, or industry was equivalent in terms of its results for growth [@Palma2005]. In Mexico, with the arrival of the economic opening process that began in the eighties and was crowned with the signing of the North American Free Trade Agreement (NAFTA), sectorial industrial policy, although it still existed in discourse, had been considerably narrowed to the point of being non-existent in practice due to its comparatively reduced budget and limited scope [@Moreno2018].

Recently, there has been a resurgence of theoretical and political interest in the central role of industrial activity in development. In the 2015 Development Agenda, the United Nations has re-evaluated the role of industry in the growth and development process [@Nieto2017]. This has translated into actions such as the one taken by the Mexican government in September 2022 through the Ministry of Economy, which announced a series of guidelines aimed at recovering industrial policy as a tool for promoting growth and economic development [@SE2022].

However, both the industrial policy of the import substitution period and recent attempts to recover this intervention tool in Latin America are still fundamentally macroeconomic in nature as they focus on specific key sectors without distinguishing the socio-territorial specificities of the regions where such activities take place [@GonzalezVillareal2017; @Gallagher2008]. In addition, these policies often do not take into account the possible benefits derived from the territorial concentration of industry that arise through agglomeration economies, that is, traditional industrial policy measures are "spatially blind" [@Fothergill2019].

Therefore, there is a need to make the heterogeneity and regional differences that characterize developing economies such as Mexico explicit within industrial policy. Furthermore, such industrial policy must be nourished by evidence-based discussion of the material inter-sectorial linkages provided by the input-output matrix, which can identify industrial complexes in the territory that are capable of generating growth and potentially development.

The objective of this study is twofold. On the one hand, it aims to identify closely related industrial activities based on their material interrelations given by the input-output matrix, i.e., industrial productive chains. On the other hand, it aims to find such chains in the national territory based on their patterns of spatial concentration, i.e., to locate industrial complexes that can be incorporated into industrial policy strategies that make the socioterritorial characteristics of the spaces where they are located explicit.

In the following section, a theoretical and empirical review of spatial concentration of economic activity and the forces that emerge from it in the form of agglomeration economies is carried out. Next, the method used for the identification of productive chains and their regionalization as industrial complexes is pointed out. Then, the results of the identification of productive chains and their territorial distribution at the municipal level in Mexico are presented, where the final conclusions and reflections derived from the results are also presented.

# 1. Agglomeration Economies and Spatial Concentrations of Economic Activity

A central theme in regional disciplines has been the set of forces shaping the economic space [@Fischer2014]. These forces, known as agglomeration economies, are linked to the advantages enjoyed by economic units with a spatially concentrated pattern [@GordonAndMacCann2000: 516]. These advantages emerge from the social and cooperative character of the production process [@Marx2011, p. 391-408] and the social division of labor [@Scott2006]. Both elements result in improved performance of economic units through an increase in labor productivity and cost reduction [@Cohen2009]. Usually, agglomeration economies are divided into two types: i) specialization economies or Marshall-Arrow-Romer (MAR) economies, which refer to the agglomeration of firms belonging to the same industry [@Glaeser1992; @Sjoholm1999: 560], and ii) urbanization economies or Jacobs economies, in which it is not specialization but the diversity and variety of economically concentrated activities that can promote innovation and growth [@Duranton2014; @VanOortAndLambooy2014].

Agglomeration economies create a certain type of spatial distribution pattern, which can be characterized as patterns of concentration of economic activity. These patterns have received different names: industrial districts, industrial complexes, industrial poles, regional production systems, regional innovation systems, clusters, among others. This conceptual variety can sometimes cause confusion because these terms are often used indiscriminately and sometimes without critical reflection on their theoretical or empirical scope. A minimum observation of the content of these terms is necessary, especially when it comes to identifying these agglomerations in order to drive their growth through industrial policy. In this section, three criteria are proposed that can contribute to better understanding and distinguishing between the multiple existing concepts related to patterns of territorial concentration of economic activity, such as: i) the development phase of capitalism in which they were coined, ii) the type of companies that are linked to the concentration, and iii) the extent of the social reality that the concept seeks to capture.

The first criterion, the development phase of the capitalism system in which the term was proposed, is a historical criterion. The various concepts that describe the patterns of concentration of economic activity were created at least a century apart, so changes in the organization of the work process due to technical progress, the use of new sources of energy, and principles of labor management affect the forces that cause such patterns and the specific form they can take. Furthermore, the form of the capitalist system has changed considerably in that time frame: from a phase of competition focused on local markets, to an oligopolistic structure of multinational companies that supply national markets, and currently, to a global network of goods suppliers governed by multinational companies through global value chains.

The first criterion warns about the historicity of concepts. For example, the term industrial district was proposed by Marshall at the beginning of the 20th century to refer to a type of society that was in extintion: the small manufacture centered on the supply of local markets [@TripplBergman2014: 450]. The industrial district term, when rescued by neo-Marshallians in the 1970s, refers to a semi-capitalist or small commercial production system in which the authority of the artisan and local tradition is relevant. The attention given to social, institutional, and cultural variables by neo-Marshallians and their emphasis on small and medium-sized enterprises somewhat recalls the era of competitive capitalism.

The second criterion is about structure: the type of companies involved in the agglomeration. The concept chosen to refer to patterns of economic activity concentration must take into consideration if the agglomeration is structured by small, medium-sized, or even multinational companies. This criterion highlights the distinction of whether the company structure has a family or corporate management; or if it has a family structure, which generation of owners runs it. For example, the Porter cluster concept is closer to the analysis of the multinational company compared to the local production system that usually describes a structure of small and medium-sized enterprises. In addition, this distinction not only relates to the size of the company but also to the origin of its capital, because the possible conflicts that could emerge on the region.

Finally, the third criterion is for delimiting and refers to the extent of the social reality that seeks to be captured through conceptual tools. Some of the concepts associated with patterns of economic activity concentration are narrower than others. This is because they focus only on the economic aspects of reality, such as input-output links, cost structure, or productivity increases, as does the concept of industrial complex or the original meaning of industrial district given by Marshall. Others are more comprehensive and capture not only the economic aspects, but also socio-cultural traits and even institutional factors, as does the concept of innovative milleaux or the regional innovation systems.

In the next lines, the most common concepts used to describe patterns of concentration of economic activity are discussed, following the previous ideas. Specifically, the concepts covered are: industrial district (Marshallian and neo-Marshallian), *innovative milieux*, growth poles, industrial cluster, territorial production system, industrial complex, and cluster. This distinction and contrast allows not only to critically select the concept used in this work, industrial complex, but also to justify the selection of the technique for the identification of said complexes.

2. Concepts on patterns of concentration of economic activity

As is well known, Marshall [-@Marshall1957] points out the causes and consequences of the agglomerations of economic activity through the term industrial districts. He links these patterns to three forces: i) transmission of knowledge (methods and techniques of production or organization of the work process), ii) development of specialized economic units that supply inputs, and iii) skilled and specialized labor. The content of the concept proposed by Marshall describes the reminiscences of the competitive phase of capitalism in which small and medium-sized companies close in space acquire advantages as a result of agglomeration economies. The emergence of these advantages allows them, under certain circumstances, to compete with the large dominant companies in a sector.

In this sense, "the Marshallian district was essentially limited to distances that could be economically covered on a daily basis by workers and suppliers by the end of the 19th century, the densities were high enough and the distances short enough for the districts to be described as 'neighborhoods'" [@TripplBergman2014: 449-450] Thus, the Marshallian concept of industrial district refers predominantly to the phase of free competition capitalism, already dying out even in the years when Marshall's "Principles" were published, and emphasizes the economic aspects of the phenomenon of spatial concentration while focusing attention on small and medium-sized companies.

During the golden age of capitalism, after World War II and before the oil price crisis of the seventies, there were several attempts to theorize about the development process from a regional perspective, sometimes focused on underdevelopment economies. Among them, Perroux's contribution stands out through the theory of growth poles. In it, economic policy measures consisted of fiscal incentives aimed at large manufacturing companies, usually multinationals, with the idea of reproducing the path development conditions experienced by previously developed regions of capitalist countries [@Garofoli2020encyclopedia: 199].

The concept of growth poles by the French theorist is consistent with the oligopolistic phase of post-war capitalist development, in which the large multinational company operates as a provider of national markets and is more or less strongly linked to small and medium-sized national companies through productive linkages. Within Perroux's conception, the agglomeration's economic factors are central, so he paid little attention to the institutional, social and cultural aspects that influenced the dynamics of the pole.

In the 1970s, amidst the widespread crisis marking the transition towards geographically fragmented production as the dominant form of production, some small and medium-sized enterprises in Northern Italy found a way to survive by taking advantage not only of geographical proximity but also of multiple social and cultural aspects that distinguished the productive activity of the region. Studies by Becattini (1979, cited by Trippl Bergman, 2014) were interested in causes of the success of the so-called Third Italy and he coin the concept of neo-Marshallian industrial districts. In this concept, economic factors are relevant, but they are far from being the only determinants of success in the regional growth process. Becattini describes his concept as "a complex socio-economic arrangement that highlights the relationship between efficiency, competitiveness in production, and prevailing sociocultural conditions at the regional level [@TripplBergman2014: 444].

Approximately in the same years, another particularly widespread concept among francophones emerges, which is used to describe regions capable of promoting growth based on innovation: *Milieux Innovateurs*. This concept is sometimes used interchangeably with the concept of network [@Gallaud2013encyclopedia]. Trippl and Bergman (2021: 444) define innovative environments as "a set of specific regional rules, practices, and institutions that improve the ability of regional actors to innovate and coordinate with other innovative actors". Similarly to the previous concept, innovative environments do not focus on economic aspects and instead highlight socio-institutional aspects that can influence innovation processes. A concept close to this one is the territorial production system, which can be conceived as an attempt to better understand the territorial aspects of the innovation process, however, the scope of this concept is much less clear (Crevoisier and Maillat, 1991; cited by Trippl and Bergman, 2014: 446).

The aforementioned concepts, both the neomarshallian industrial district, the innovative environment, and the territorial production system, emerge during the transition phase from oligopoly, organized through Fordist and Taylorist production processes, to the phase of globally open markets and connected through spatially fragmented production chains where flexible production systems play a significant role. Additionally, these concepts pay much greater attention to the social, institutional, and cultural factors that can drive or condition the economic success of small and medium-sized enterprises linked to the multinational corporations that command the production chain.

Probably the most popular concept aimed at describing the patterns of spatial concentration of economic activity is the term "cluster." This term was popularized in the last decade of the 20th century thanks to Porter's works on corporate strategies. This concept refers to multinational companies and pays much greater attention to the competition aspects among the actors that form up the so-called cluster. A cluster can be defined as "geographic concentrations of interconnected companies, specialized suppliers, service providers, related industry companies, and associated institutions in particular fields that compete but also cooperate" (Porter 1998, cited by Trippl and Bergman 2014: 447). Nonetheless, the concept has received multiple criticisms due to its ambiguity and lack of precision on its geographic and sectorial boundaries, as well as the limited attention paid to social factors [@MartinSunley2003; @Pacheco2007].

Another concept that is commonly used in urban economics studies is that of the industrial complex [@GonzalezVillareal2017], which "are characterized by identifiable and stable sets of relationships between companies that are manifested in part in their spatial behavior. The relationships are mainly conceived in terms of commercial links, and it is these patterns of sales and purchases that primarily govern their location behavior" [@GordonAndMacCann2000: 518]. This concept emerges approximately in the same phase of transition, but unlike the others, it focuses much more notably on quantifiable material economic factors, i.e. on input-output relationships, so social or institutional aspects are not within its scope, but it also does not distinguish between the type of companies participating in it.

The brief enumeration of some of the terms used to describe the spatial patterns of concentration of economic activity is, of course, far from exhaustive. Nevertheless, according to the criteria pointed out, it is possible to place them historically and to distinguish the aspects of reality they seek to capture. The concept of the industrial complex, which focuses only on the material interrelationships between economic units given by input-output links and does not distinguish between the structure of companies, will guide the rest of our exposition, and it fit to the scope of the method proposed for the identification of such complexes.

# 3. The Study of Spatial Concentrations of Economic Activity in Mexico

In Mexico, interest in the study of concentrations of economic activity is not new; however, the critical distinction of the category that describes the patterns of territorial concentration of economic activity is not usual. In this section, we present some of the most recent works that, for the case of the Mexican economy, seek to identify territorial concentrations of economic activity.

Some of the studies for Mexico focus on the changes in location patterns brought about by the economic liberalization process [@TrejoNieto2013; @GomezZaldivar2017] or the economic integration that it caused [@Davila2008]. Others focus on the study of specific sector groups, where the causes of their origin are investigated, such as the grouping of the aerospace industry in Querétaro [@GarzaBurgos2018], or they carry out a contrast of the specific characteristics of a grouping, such as that of footwear [@LopezHernandez2018], with the canonical characteristics of groupings from a certain theoretical perspective [@Rabellotti1995]; while others evaluate the performance of the groupings present in specific regions [@JimenezAlmaguer2013].

Other studies have focused on the methods of delimiting and identifying such clusters within the national territory, and then investigating their performance. The study of García and Carranco [-@GarciaCastro2008] and García et al. [-@GarciaCastro2009] start from the definition of what they call a local productive cluster and propose a simple method for its identification and evaluation. On the other hand, Mendoza-Velázquez [-@MendozaVelazquez2017] refers to Porter's proposal (1998, 2003, cited by Mendoza-Velázquez 2017) to define clusters.

In relation to the identification of industrial complexes, although they are not always referred to as such, there are the works of Laguna-Reyes [-@LagunaReyes2010], González et al. [-@GonzalezVillareal2017], and Trejo y Negrete [-@TrejoNieto2018]. Their aim is to identify clusters in the national territory based on the interrelationship given by the input-output links, using the conglomerate analysis method developed by Feser and Bergman [-@Feser2000].

The work by Laguna Reyes [-@LagunaReyes2010: 199] "analyzes and applies a methodology for identifying productive chains as a reference for the analysis of the economic base of regional industrial clusters" (p. 119). The author conceives the groups, which he calls clusters, as "concentrations of interconnected companies and institutions in a particular field that compete and cooperate" (p. 119), although he acknowledges that there is no fully clear definition of the meaning of an industrial cluster, for this reason, he bases the identification only on economic aspects by indicating that these groups are "a set of sectors that use relatively large amounts of each other's products" (p. 123). In this sense, the author are identifying what we call here industrial complexes.

Trejo and Negrete [-@TrejoNieto2018] set themselves three objectives: i) to review the economic structure, performance and changes of the central region of Mexico (RECEMEX), ii) to identify the most relevant economic sectors of the region through the estimation of a regional input-output matrix and to identify the clusters present in this region, and iii) to establish the performance of these groups. Regarding point ii, they use the method of Feser and Bergman (2000) with which "they identify six clusters in the economy of the RECEMEX, which group 21 of the 28 sectors" (p. 24).

The study by González Villareal [@GonzalezVillareal2017] aims to identify industrial complexes in Mexico in order to provide economic policy ideas for these concentration spaces in the context of smart specialization and related variety, measures inspired by the regional policy strategies of the European Union [@Balland2019; @Frenken2007]. Among the results that the authors reach is the identification of 5 productive chains: manufacture of electronic components, automobiles, chemicals, textiles and clothing and processed agricultural and food products, as well as their distribution at the municipal level in Mexico.

In the following section, the methodology for the identification of industrial complexes is presented, which, based on the works of Feser and Bergman (2000) and Feser et al. (2005), seeks to more precisely distinguish and classify territorial concentrations of economic activity in the municipalities of Mexico.

# 4. Identification of Patterns of Agglomeration of Economic Activity

Methods for identifying patterns of agglomeration of economic activity are varied. Multiple studies in regional economics use measures of agglomeration or specialization[@Kopczewska-etal2017; @Komorowski2020; @Gleave-etal2004; @GarciaCastro2008], or conduct case studies from a business management perspective [@Piccinetti2015]. However, from a purely technical standpoint, the delimitation of activity concentrations can be reduced to pattern identification, allowing for computational methods such as cluster analysis [@Adolfsson-etal2018].

The input-output matrix can be considered a tool that illustrates the proximity or similarity between the economic activities that make it up. The greater the relationship between economic sectors through their interactions in the form of purchases and sales, the closer they will be and form activity groupings or production chains. From this perspective, the relationship between sectors can be analyzed through various computational methods, such as graph theory, network theory, triangulation methods, and factor analysis through principal components.


Multiple studies use methods based on the identification of input-output links in a national economy and most of them make use of the work of Feser and Bergman [-@FeserBergman2000; @Feser-etal2005; @Sonis2008; @Delgado-etal2016; @GonzalezVillareal2017; @LagunaReyes2010; @TrejoNegrete2018]. This work proposes an approach based on the classic proposal of Feser and Bergman [-@FeserBergman2000] and Feser et al. [-@Feser-etal2005] for the identification of production chains and their spatialization, that is, for the identification of industrial complexes.

The method proposed in this work is divided into two main steps: first, the identification of sets of strongly interrelated economic activities through their input-output links is carried out, that is, first production chains are identified given by patterns of purchases and sales at the level of the entire economy. Then, the production chains are located in the national geographic space at the municipal level through the recognition of patterns of spatial interaction in the use of these chains.

## 4.1 Identification of the production chains

The input-output matrix (IOM) is a tool that allows to know the inter-sectoral relationships between the economic activities that take place in a national economy through the record of the purchases and sales that take place between them [@INEGI2018cn]. The IOM provides the monetary value of the goods sold by the activity of row $i$ to the activity of column $j$, $a_{ij}$, that is, the sales made by sector $i$ to sector $j$. Let $p$ and $s$ be the value of the total intermediate purchases and the total intermediate sales, respectively; thus, the relationship between each pair of activities, $i$ and $j$, can be characterized from the following coefficients [@Feser2000, p. 6]:

$$
x_{ij}=\frac{a_{ij}}{p_j};
x_{ji}=\frac{a_{ji}}{p_i};
y_{ij}=\frac{a_{ij}}{s_j};
y_{ji}=\frac{a_{ji}}{s_i}
$$ 

Feser and Bergman (2000: 5) explain these previous coefficients in the following manner:

"$x_{ij};x_{ji}$: intermediate goo  d purchases by $j$ ($i$) to $i$ ($j$) as  a proportion of $j´s$ ($i´s$)  total intermediate good purchases. A large value for $x_{ij}$, for example, suggests that industry $j$ depends on industry $i$ as a source for a large proportion of its total intermediate inputs.

$y_{ij}; y_{ji}$: intermediate good sales from $i$ ($j$) to $j$ ($i$) as a proportion of $i´s$ ($j´s$). total intermediate good sales. A large value of $y_{ij}$, for example, suggests that $i$ depends on industry $j$ as a market for a large proportion ofits total intermediate good sales".

The previous coefficients can be synthesized into two matrices: $X$ and $Y$, referred to as the purchasing proportion matrix and the sales proportion matrix, respectively. A correlation analysis is performed on matrices $X$ and $Y$, consisting of constructing four matrices whose elements correspond to the degree of association between pairs of activities, say $l$ and $m$. Again, following Feser and Bergman (2000: 5):

"$r(x_l\cdot x_m)$: measures the degree to which industries $l$ and $m$ have similar input purchasing patterns

$r(y_l\cdot y_m)$: measures the degree to which $l$ and $m$ possess similar output selling patterns, i.e. the degree to which they sell goods to a similar mix of intermediate input buyers

$r(x_l\cdot y_m)$: measures the degree to which the buying pattern of industry $l$ is similar to the selling pattern of industry $m$, i.e . the degree to which industry $l$ purchases inputs from industries in wich $m$ supplies. 

$r(y_l\cdot x_m)$: measures the degree to which the buying pattern of industry $m$ is similar to the selling pattern of industry $l$, i.e. the degree to which industry $m$ purchases inputs from industries in which $l$ supplies".

Subsequently, with the four matrices obtained, another matrix is constructed that contains only the highest correlation coefficients between pairs of activities. This matrix "shows the most important interrelations between pairs of economic industries" [@GonzalezVillareal2017: 5], that is, synthesizes the most intense patterns of purchases and sales between each pair of sectors.

Finally, to obtain the sets of activities that make up the production chains, the Principal Component Analysis (PCA) is used on this last matrix. Essentially, the principal component analysis, one of the most commonly used multivariate statistics techniques, aims to reduce the number of dimensions or variables of a set of correlated data, to a smaller one that is not [@Abdi2010]. The technique aims to find the most similar or similar economic activities based on their patterns of purchases and sales.

The PCA that has been followed can be divided into the following steps:

i) Calculation of the principal components.
ii) Selection of the number of components from the sedimentation graph and the percentage of variance that each component explains.
iii) Rotation of the components through the varimax method in order to better understand the loads obtained.  
iv) Selection of the activities that make up each production chain based on the value of their rotated loads.

The selection of the activities that make up each production chain is done by observing the loads within each grouping. Again, Feser and Bergman (2000): "the generated set of loads provides a measure of the relative strength of the links between a given industry (economic activity) and the derived factor (production chain to which it belongs), where industries with the highest loads of a given factor are treated as members of a production chain" (p. 4), which allows to distinguish between different types of activities within each production chain such as primary and secondary activities. Primary activities are those that, for a specific chain, have a load value equal to or greater than 0.6, while a secondary activity is one that has a load between 0.35 and 0.6.

As a result, after careful observation of each of the obtained components, groupings of activities that can be defined as production chains are obtained. The approach of Feser and Bergman (2000) is useful because "the method based on the extraction of linkages from the input-output model allows the use of a general pattern of groupings, which provides a framework for making comparisons between regions" [@LagunaReyes2010, p. 126], that is, it becomes the first step for then regionalizing the results.

Among the main advantages of this approach is "that it allows the identification of production chains in the regional sphere, from the national grouping patterns. This makes it possible to identify the gaps between local supply chains in comparison to the national ones, which makes it possible to determine areas of specialization, regional competitive advantages and regional development opportunities" [@LagunaReyes2010, p. 127].

On the other hand, Trejo and Negrete [-@TrejoNieto2018, citing Dávila, 2008] mention that "this method meets five criteria that make it a useful tool for identifying groupings, when input-output information is available, which are: a) reliability; b) ability to generate results in the short term; c) low instrumentation cost; d) possibility of sectoral disaggregation of information and e) flexibility to visualize the presence of clusters (territorial concentrations of activity) in different geographical areas" (p. 21).

However, among the disadvantages is that "using the national economy as an implicit reference assumes that the technological, labor productivity and consumption pattern differences between the national economy and local economies are null, which can be misleading, especially in cases where the region truly specializes in a particular production chain" [@LagunaReyes2010,p. 127].

## 4.2 Identification of Regional Industrial Complexes

The proposal for the identification of territorialized productive chains is based on to the calculation of local spatial autocorrelation indicators, according to Feser et al. [-@Feser-etal2005] method, adapted from the considerations of Anselin [-@Anselin2020local2]. Thus, the objective is to spatially locate the industrial productive chains found through the Feser and Bergman method [-@Feser2000] that were the result of the PCA, exposed in the previous section.

Feser et al. [-@Feser-etal2005] and González Villarreal et al. (2017) use the local spatial association statistic of Getis-Ord ($G_i^*$) [@Getis1992] for the identification of complexes. Here we use the local spatial association statistic of Moran, originally proposed by Anselin [-@Anselin1995], and has the form of:

$$
I_i = c \cdot z_i \sum_j w_{ij} z_j
$$

The notation above corresponds to Anselin [-@Anselin2020local2], in which $I_i$ is the Moran's Local Spatial Association Statistic, $z_i$ and $z_j$ corresponds to the value of the standardized variable in territorial unit $i$ and $j$, which is usually employment, while $w_{ij}$ is each element of the row-standardized spatial weight matrix, and finally $c$ is a constant given by $\sum_i z_i^2$, the sum of the standardized variable value.

The $I_i$ can be represented in cluster maps with four categories of territorial units: i) clusters of territorial units with high variable values surrounded by neighboring territorial units also with high values (High-High clusters); ii) clusters of territorial units with low variable values surrounded by neighbors with the same characteristic (Low-Low clusters); iii) clusters of territorial units with low variable values surrounded by neighbors with high values (Low-High clusters); and iv) clusters of territorial units with a high value variable surrounded by others with a low value (High-Low clusters).

When "high" or "low" is mentioned here, it is in relative terms, i.e., low or high values within the range of the information used. The last two categories, the Low-High and High-Low groups, identify territorial units as spatial outliers.

In order to control the size of the employment in the considered regions, we estimate the local indicator of spatial association with the residuals, $u_i$, of a linear regression estimated with ordinary least squares of the employment of each of the industrial chains in each municipality over the total employment of that municipality [@GonzalezVillareal2017, p. 6; @Feser-etal2005, p. 403], so $I_i$ index is built using the error terms [^1] that is:

$$
emp_i=\beta_0+\beta_1empCPi+u_i
$$
Where $emp_i$ is the total employment in spatial unit $i$, $empCPi$ corresponds to the employment of the considered production chain in spatial unit $i$. Nevertheless, the approach of Feser et al. (2005) and Villarreal et al. (2017) has some weaknesses, which are listed below, as well as a proposal to remedy them in this work.

## Differences with previous approaches

In previous work by Feser and Bergman (2005) and Villarreal et al. (2017), the Getis-Ord index was used to classify the spatial units into just two categories, high and low, with those in the high category constituting the clusters.

However, using the Moran's I index allows for a more nuanced categorization of territorial units and identification of spatial outliers. This leads to a clearer distinction between those territorial units that actually form a solid industrial complex, given their patterns of spatial autocorrelation, and those that potentially could.

Specifically, a territorial unit or group of contiguous or nearby territorial units will be considered an industrial complex if they fall into the High-High category. Meanwhile, territorial units classified in the High-Low category will not be considered industrial complexes, but they will be of interest for regional industrial policy measures aimed at promoting activity not just within the territorial unit, but also among its neighbors, leveraging spillover effects and agglomeration economies.

## 4.3 Data Sources and Territorial Unit of Analysis

For the identification of productive chains at the national level, the most recent input-output matrix information is used, corresponding to the year 2013 [@INEGI2018cn], classified according to the North American Industrial Classification System, NAICS, [@INEGI2018scian]. Therefore, the $X$ and $Y$ matrices are square matrices of 263x263.

The geographical database used comes from the National Geo-statistical Framework (Marco Geoestadístico Nacional) [@INEGI2020mgn], which contains 2,469 municipal geo-statistical areas (municipalities), for which a queen-type spatial weight matrix of order 1 was constructed. The information on employed personnel (employment) corresponds to the year 2013 and comes from the 2019 Economic Censuses [@INEGIce2020].

# 5. Results and Conclusions

The PCA produced a total of 25 components, which explain 92% of the variance. From them, 9 correspond to industrial productive chains, in contrast with the five chains identified  by Villarreal et al. (2017) in the 2008 input-output matrix. The obtained results are summarized in Table 1, which shows the number of municipalities that were identified in the High-High category for each chain and, therefore, constitute industrial complexes; In addition, the municipalities that appear in the High-Low category are also shown, which can be incentivized to join industrial complexes.

| Productive chain                        | High-High municipalities | High-Low municipality | More strongly linked branches                                                                                                    |
|------------|------------|------------|------------------------------------|
| Metalmecánica.                           | 71                   | 11                   | 3327, 3312, 3315, 3329, 3328, 3362, 3322, 3311, 3365, 3335, 3334, 3324, 3366, 3323, 3352, 3325, 3321, 3339, 8113, 3331, 3313, 4889. |
| Química.                                 | 63                   | 24                   | 3256, 3252, 3259, 3253, 2111, 5621, 3255, 3254, 3251, 3121, 3272.                                                                   |
| Eléctrico-electrónica.                   | 81                   | 8                    | 3344, 3342, 3341, 3333, 5172, 3343, 3345, 3351, 3332, 3359, 3353, 5171, 8112, 4885.                                                 |
| Textiles, confección y prendas de vestir | 75                   | 7                    | 3141, 3151, 3159, 3152, 3149, 3133, 3132, 3379, 3169, 3391, 3162.                                                                   |
| Construcción.                            | 73                   | 23                   | 2379, 2372, 2361, 2362, 2381, 2371, 3273, 2389, 2373, 3271, 3279.                                                                   |
| Autotransportes.                         | 69                   | 11                   | 3361, 8111, 3369, 5321, 3363, 8114.                                                                                                 |
| Papel e impresión.                       | 79                   | 6                    | 3222, 3221, 3231, 5615, 5619, 8129, 5613.                                                                                           |
| Plásticos y fibras sintéticas.           | 64                   | 18                   | 3261, 3346, 3262, 3399, 3131.                                                                                                       |
| Muebles y productos de madera.           | 59                   | 14                   | 3372, 3326, 3212, 3219, 3371.                                                                                                       |

: Tabla 1. Complejos industriales, 2013